### ISSUE TITLE
Support for k8s 1.22 

### ISSUE THREAD

**Issue by pulpo** [ibuildthecloud/klum#4]
I had updated a cluster to version 1.22, and found that klum is not able to find resources anymore (was working up to 1.21)

```
time="2021-11-12T17:22:54Z" level=info msg="Starting klum controller"
time="2021-11-12T17:22:54Z" level=fatal msg="the server could not find the requested resource"
```
Is there any roadmap to bring support again for newer kubernetes versions or this project is not anymore into active development?

**Comment by jadolg** [comment]
I created a PR (https://github.com/ibuildthecloud/klum/pull/5) with updated dependencies that is working for me. @ibuildthecloud would you please give it a quick review? Thank you for this convenient piece of software :-)
